services:
  mongodb:
    image: mongo:latest
    container_name: glue_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - glue_network

  nest_app:
    container_name: glue_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: ${MONGO_URI}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - glue_network

volumes:
  mongo_data:

networks:
  glue_network:
